apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
  namespace: development
  labels:
    app: billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      namespace: development
      labels:
        app: billing
    spec:
      containers:
      - name: billing
        image: registry.gitlab.com/pshenmic/ivend/billing:develop
        imagePullPolicy: Always
        ports:
        - containerPort: 3500
        envFrom:
          - configMapRef:
              name: billing-config
      imagePullSecrets:
      - name: gitlabregistrycred
